name: opra-separation

services:
  db:
    image: postgres:15
    container_name: opra_postgres_sep
    restart: always
    environment:
      POSTGRES_DB: opra_sep
      POSTGRES_USER: opra_user
      POSTGRES_PASSWORD: opra_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_sep:/var/lib/postgresql/data

  web:
    build: .
    container_name: opra_web_sep
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    env_file:
      - ./compsocsite/.env
    environment:
      - DATABASE_URL=postgres://opra_user:opra_password@db:5432/opra_sep
    depends_on:
      - db

volumes:
  postgres_data_sep:
