# Generated by Django 4.2.7 on 2023-12-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0018_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
