# Generated by Django 4.2.7 on 2023-12-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0019_userprofile_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='salt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
