# Generated by Django 4.2.7 on 2024-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appauth", "0023_alter_userprofile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_user_info",
            field=models.IntegerField(default=1),
        ),
    ]
