# Generated by Django 4.2.7 on 2025-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0024_userprofile_display_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_code_user',
            field=models.BooleanField(default=False),
        ),
    ]
