# Generated by Django 4.2.7 on 2026-04-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0025_userprofile_is_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code_source',
            field=models.CharField(default='polls', max_length=20),
        ),
    ]
