# Generated by Django 4.2.7 on 2026-04-10 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockElectionDictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MockElectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_text", models.CharField(max_length=200)),
                (
                    "item_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/img/items/"
                    ),
                ),
                ("imageURL", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "imageReference",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("timestamp", models.DateTimeField(verbose_name="item timestamp")),
                ("recently_added", models.BooleanField(default=False)),
                ("utility", models.FloatField(default=0.0)),
                ("self_sign_up_user_id", models.TextField(default="")),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MockElectionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("question_desc", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/img/items/"
                    ),
                ),
                ("imageURL", models.CharField(blank=True, max_length=500, null=True)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "recentCSVText",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("status", models.IntegerField(default=1)),
                ("display_pref", models.IntegerField(default=1)),
                ("display_user_info", models.IntegerField(default=1)),
                ("creator_pref", models.IntegerField(default=1)),
                ("emailInviteCSV", models.BooleanField(default=False)),
                ("emailInvite", models.BooleanField(default=False)),
                ("emailDelete", models.BooleanField(default=False)),
                ("emailStart", models.BooleanField(default=False)),
                ("emailStop", models.BooleanField(default=False)),
                ("poll_algorithm", models.IntegerField(default=1)),
                ("question_type", models.IntegerField(default=1)),
                ("winner", models.CharField(default="", max_length=200)),
                ("mixtures_pl1", models.TextField(default="")),
                ("mixtures_pl2", models.TextField(default="")),
                ("mixtures_pl3", models.TextField(default="")),
                ("m_poll", models.BooleanField(default=False)),
                ("next", models.IntegerField(default=-1)),
                ("first", models.IntegerField(default=-1)),
                ("open", models.IntegerField(default=0)),
                ("new_vote", models.BooleanField(default=False)),
                ("twocol_enabled", models.BooleanField(default=True)),
                ("onecol_enabled", models.BooleanField(default=True)),
                ("slider_enabled", models.BooleanField(default=True)),
                ("star_enabled", models.BooleanField(default=True)),
                ("yesno_enabled", models.BooleanField(default=True)),
                ("yesno2_enabled", models.BooleanField(default=False)),
                ("single_enabled", models.BooleanField(default=False)),
                ("budgetUI_enabled", models.BooleanField(default=False)),
                ("ListUI_enabled", models.BooleanField(default=False)),
                ("infiniteBudgetUI_enabled", models.BooleanField(default=False)),
                ("allowties", models.BooleanField(default=True)),
                ("initial_ui", models.IntegerField(default=1)),
                ("ui_number", models.IntegerField(default=6)),
                ("vote_rule", models.IntegerField(default=4095)),
                ("alloc_res_tables", models.IntegerField(default=6)),
                ("alloc_algorithms", models.IntegerField(default=0)),
                ("first_tier", models.IntegerField(default=0)),
                ("utility_model", models.IntegerField(default=0)),
                ("results_visible_after", models.DateTimeField(blank=True, null=True)),
                ("correct_answer", models.TextField(default="")),
                ("allow_self_sign_up", models.IntegerField(default=0)),
                (
                    "follow_up",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionquestion",
                    ),
                ),
                (
                    "question_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question_voters",
                    models.ManyToManyField(
                        related_name="mock_election_participated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockElectionVoteResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_string", models.TextField(default="")),
                ("mov_string", models.TextField(default="")),
                ("cand_num", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(verbose_name="result timestamp")),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MockElectionUserVoteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="record timestamp")),
                ("user", models.CharField(default="(Anonymous)", max_length=100)),
                ("record", models.CharField(default="", max_length=10000)),
                ("col", models.TextField(default="")),
                ("one_col", models.TextField(default="")),
                ("slider", models.TextField(default="")),
                ("star", models.TextField(default="")),
                ("swit", models.TextField(default="")),
                ("initial_order", models.TextField(default="")),
                ("initial_type", models.IntegerField(default=0)),
                ("final_order", models.TextField(default="")),
                ("device", models.CharField(default="", max_length=20)),
                ("comment_time", models.CharField(default="", max_length=100)),
                ("submit_time", models.CharField(default="", max_length=100)),
                ("ui", models.CharField(default="", max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MockElectionUnregisteredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "polls_invited",
                    models.ManyToManyField(
                        related_name="invited_unregistered_users",
                        to="mock_election.mockelectionquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockElectionSignUpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.TextField()),
                ("status", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(verbose_name="request timestamp")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockElectionScoreMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionvoteresult",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MockElectionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resp_str", models.CharField(blank=True, max_length=1000, null=True)),
                ("timestamp", models.DateTimeField(verbose_name="response timestamp")),
                (
                    "anonymous_voter",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("anonymous_id", models.IntegerField(default=0)),
                ("comment", models.CharField(blank=True, max_length=1000, null=True)),
                ("active", models.IntegerField(default=1)),
                ("behavior_data", models.TextField(default="")),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionitem",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MockElectionOldWinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionquestion",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionresponse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockElectionMoV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionvoteresult",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MockElectionLoginCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_codes",
                        to="mock_election.mockelectionquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_election_login_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockElectionKeyValuePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(db_index=True, default=0)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectiondictionary",
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mockelectionitem",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mock_election.mockelectionquestion",
            ),
        ),
        migrations.CreateModel(
            name="MockElectionFinalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_string", models.TextField(default="")),
                ("mov_string", models.TextField(default="")),
                ("node_string", models.TextField(default="")),
                ("edge_string", models.TextField(default="")),
                ("shade_string", models.TextField(default="")),
                ("cand_num", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(verbose_name="result timestamp")),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockElectionEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField()),
                ("subject", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=500)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionquestion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mockelectiondictionary",
            name="response",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="mock_election.mockelectionresponse",
            ),
        ),
        migrations.CreateModel(
            name="MockElectionCandScorePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cand", models.IntegerField(default=0)),
                ("score", models.FloatField(default=0.0)),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mock_election.mockelectionscoremap",
                    ),
                ),
            ],
        ),
    ]
