# Generated by Django 4.2.7 on 2026-05-01 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mock_election", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockelectionitem",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_set",
                to="mock_election.mockelectionquestion",
            ),
        ),
        migrations.AlterField(
            model_name="mockelectionresponse",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_set",
                to="mock_election.mockelectionquestion",
            ),
        ),
        migrations.AlterField(
            model_name="mockelectionsignuprequest",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signuprequest_set",
                to="mock_election.mockelectionquestion",
            ),
        ),
        migrations.AlterField(
            model_name="mockelectionvoteresult",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voteresult_set",
                to="mock_election.mockelectionquestion",
            ),
        ),
    ]
