# Generated by Django 4.2.7 on 2026-05-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mock_election", "0003_alter_mockelectionitem_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockelectionsignuprequest",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mock_election.mockelectionquestion",
            ),
        ),
        migrations.AlterField(
            model_name="mockelectionvoteresult",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mock_election.mockelectionquestion",
            ),
        ),
    ]
