# Generated by Django 4.2.7 on 2026-05-04 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mock_election", "0004_alter_mockelectionsignuprequest_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockElectionClasses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("startDate", models.DateField(verbose_name="start date")),
                ("weekly", models.IntegerField(default=0)),
                ("attendance", models.IntegerField(default=-1)),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="mock_election_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teachingAssistants",
                    models.ManyToManyField(
                        related_name="mock_election_tas", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mockelectionquestion",
            name="related_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mock_election.mockelectionclasses",
            ),
        ),
    ]
