# Generated by Django 4.2.7 on 2026-06-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_election", "0005_mockelectionclasses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockelectionquestion",
            name="district",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="mockelectionquestion",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
