# Generated by Django 4.2.7 on 2026-06-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_election", "0006_add_state_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockelectionquestion",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
