# Generated by Django 4.2.7 on 2026-04-09 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_allocationlogincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationquestion')),
            ],
        ),
    ]
