# Generated by Django 4.2.7 on 2026-04-09 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allocation', '0004_allocationemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationSignUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(verbose_name='request timestamp')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocationquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
