# Generated by Django 4.2.7 on 2026-04-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_allocationsignuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationquestion',
            name='allowties',
            field=models.BooleanField(default=True),
        ),
    ]
