# Generated by Django 4.2.7 on 2024-03-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0127_question_listui_enabled_question_budgetui_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="infiniteBudgetUI_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
