# Generated by Django 4.2.7 on 2024-05-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0128_question_infinitebudgetui_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="alloc_res_tables",
            field=models.IntegerField(default=6),
        ),
    ]
