# Generated by Django 4.2.7 on 2024-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0129_question_alloc_res_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="alloc_algorithms",
            field=models.IntegerField(default=1),
        ),
    ]
