# Generated by Django 4.2.7 on 2024-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0131_question_recentcsvtext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="questions",
            field=models.ManyToManyField(
                related_name="unregistered_users", to="polls.question"
            ),
        ),
        migrations.CreateModel(
            name="UnregisteredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "polls_invited",
                    models.ManyToManyField(
                        related_name="invited_unregistered_users", to="polls.question"
                    ),
                ),
            ],
        ),
    ]
