# Generated by Django 4.2.7 on 2024-06-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0132_alter_folder_questions_unregistereduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="questions",
            field=models.ManyToManyField(to="polls.question"),
        ),
    ]
