# Generated by Django 4.2.7 on 2024-07-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0133_alter_folder_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="emailInviteCSV",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="emailDelete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="emailInvite",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="emailStart",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="emailStop",
            field=models.BooleanField(default=False),
        ),
    ]
