# Generated by Django 4.2.7 on 2024-07-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0134_question_emailinvitecsv_alter_question_emaildelete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="display_user_info",
            field=models.IntegerField(default=1),
        ),
    ]
