# Generated by Django 4.2.7 on 2025-03-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0135_question_display_user_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mechanism_id", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("preferences_hash", models.CharField(max_length=64)),
                ("hits", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
            ],
            options={
                "unique_together": {("question", "mechanism_id", "preferences_hash")},
            },
        ),
    ]
