# Generated by Django 4.2.7 on 2025-04-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0136_allocationcache"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allocationcache", old_name="hits", new_name="hit_count",
        ),
        migrations.RenameField(
            model_name="allocationcache", old_name="last_updated", new_name="timestamp",
        ),
        migrations.AlterUniqueTogether(name="allocationcache", unique_together=set(),),
        migrations.AddField(
            model_name="allocationcache",
            name="allocation_data",
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="allocationcache",
            name="hash_key",
            field=models.CharField(default={}, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(model_name="allocationcache", name="mechanism_id",),
        migrations.RemoveField(model_name="allocationcache", name="preferences_hash",),
        migrations.RemoveField(model_name="allocationcache", name="question",),
    ]
