# Generated by Django 4.2.7 on 2025-04-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0137_rename_hits_allocationcache_hit_count_and_more"),
    ]

    operations = []
