# Generated by Django 4.2.7 on 2025-04-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0138_create_allocation_cache_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="alloc_algorithms",
            field=models.IntegerField(default=0),
        ),
    ]
