# Generated by Django 4.2.7 on 2025-04-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0139_remove_default_round_robin"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="imageReference",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
