# Generated by Django 4.2.7 on 2026-05-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0144_remove_allocationvoter_allocationcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvaluepair',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='polls.dictionary'),
        ),
    ]
